obj-$(CONFIG_GX_MTC) := gx_mtc.o

EXTRA_CFLAGS += -Idrivers/misc/nationalchip/gxsecure/include/ 
EXTRA_CFLAGS += -Idrivers/misc/nationalchip/gxsecure/include/acpu 
EXTRA_CFLAGS += -Idrivers/misc/nationalchip/gxsecure/include/module
EXTRA_CFLAGS += -Idrivers/misc/nationalchip/gxsecure/drivers/include
