obj-$(CONFIG_NATIONALCHIP_COUNTER) += nc_counter.o

obj-y += gx_mem_info.o
obj-y += gx_chip_id.o

obj-$(CONFIG_GX_IRR)        += gx_irr/
obj-$(CONFIG_GX_PT2264)     += gx_irr/

obj-$(CONFIG_GX_SMARTCARD)  += smartcard/
obj-$(CONFIG_GX_GPIO)       += gx_gpio/
obj-$(CONFIG_GX_OTP)        += gx_otp/
obj-$(CONFIG_GXLOWPOWER)    += gxlowpower/
obj-$(CONFIG_GX_MTC)        += gx_mtc/

obj-$(CONFIG_GXSECURE)      += gxsecure/
obj-$(CONFIG_GX_GUESTBUS)   += guestbus/
